Repository canonical/deployment-configs, pull requests merged in 2018-05, with the labels that each got.

#128 Update Nginx Ingress annotation name
  ingresses/production/canonical.com.yaml
  ingresses/production/cloud-init.io.yaml
  ingresses/production/conjure-up.io.yaml
  ingresses/production/maas.io.yaml
  ingresses/production/snapcraft.io.yaml
  ingresses/staging/beta.staging.ubuntu.com.yaml
  ingresses/staging/cn.staging.ubuntu.com.yaml
  ingresses/staging/design.staging.ubuntu.com.yaml
  ingresses/staging/developer.staging.ubuntu.com.yaml
  ingresses/staging/docs.staging.conjure-up.io.yaml
  ingresses/staging/docs.staging.jujucharms.com.yaml
  ingresses/staging/docs.staging.maas.io.yaml
  ingresses/staging/docs.staging.snapcraft.io.yaml
  ingresses/staging/docs.staging.ubuntu.com.yaml
  ingresses/staging/docs.staging.vanillaframework.io.yaml
  ingresses/staging/insights.staging.ubuntu.com.yaml
  ingresses/staging/jp.staging.ubuntu.com.yaml
  ingresses/staging/staging.canonical.com.yaml
  ingresses/staging/staging.cloud-init.io.yaml
  ingresses/staging/staging.conjure-up.io.yaml
  ingresses/staging/staging.maas.io.yaml
  ingresses/staging/staging.netplan.io.yaml
  ingresses/staging/staging.snapcraft.io.yaml
  ingresses/staging/tutorials.staging.ubuntu.com.yaml
  ingresses/staging/usn.staging.ubuntu.com.yaml
  templates/staging.yaml
Labels: Review: Code -1, Review: QA needed

#132 Redirect to blog using https
  ingresses/production/insights.ubuntu.com.yaml
  ingresses/staging/insights.staging.ubuntu.com.yaml
Labels: Review: Code +1, Review: QA +1

#142 Revert netplan.io health check path from 9e9a1df
  services/netplan.io.yaml
Labels: Review: Code +1

#145 Set 360 to use configurable tag
  services/360.canonical.com.yaml
Labels: Review: Code +1
