Repository canonical/deployment-configs, pull requests merged in 2019-06, with the labels that each got.

#219 Disable "includeSubdomains" in HSTS
  config.global.yaml
  qa-deploy
Labels: Review: Code +1, Review: QA +1

#222 ubuntu-com.internal -> ubuntu.com, add redirects
  ingresses/production/ubuntu-com-internal.yaml
  ingresses/production/ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#223 Add sentry env var to ubuntu.com
  services/ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#226 Add sentry configuration canonical.com
  services/canonical-com.yaml
Labels: Review: Code +1

#228 Redirect blog to ubuntu.com
  ingresses/production/blog-ubuntu-com.yaml
  ingresses/production/ubuntu-com.yaml
  ingresses/staging/blog-staging-ubuntu-com.yaml
  ingresses/staging/staging-ubuntu-com.yaml
  services/blog-ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#229 Redirect insights.ubuntu.com to ubuntu.com/blog
  ingresses/production/ubuntu-com.yaml
Labels: Review: Code needed, Review: QA needed

#230 Revert /blog redirect work for now
  ingresses/production/blog-ubuntu-com.yaml
  ingresses/production/ubuntu-com.yaml
  ingresses/staging/blog-staging-ubuntu-com.yaml
  ingresses/staging/staging-ubuntu-com.yaml
  services/blog-ubuntu-com.yaml
Labels: Review: Code needed, Review: QA needed

#227 Configs for old-docs.maas.io
  ingresses/production/old-docs-maas-io.yaml
  ingresses/staging/old-docs-staging-maas-io.yaml
  services/old-docs-maas-io.yaml
Labels: Review: Code +1, Review: QA +1

#232 Redirect blog.ubuntu.com -> ubuntu.com/blog
  ingresses/production/blog-ubuntu-com.yaml
  ingresses/production/landscape-brochure-internal.yaml
  ingresses/production/ubuntu-com.yaml
  ingresses/staging/blog-staging-ubuntu-com.yaml
  ingresses/staging/landscape-brochure-staging-internal.yaml
  ingresses/staging/staging-ubuntu-com.yaml
  services/blog-ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1
