Repository canonical/deployment-configs, pull requests merged in 2019-12, with the labels that each got.

#286 Preserve live environment variables for 360
  sites/360.canonical.com.yaml
Labels: Review: Code needed, Review: QA needed

#287 Remove webteam-kpi-webhook - we dont use it
  sites/webteam-kpi-webhook.canonical.com.yaml
Labels: Review: Code needed, Review: QA needed

#290 Add useProxy property for some projects
  sites/microk8s.io.yaml
  sites/mir-server.io.yaml
  sites/multipass.run.yaml
  sites/netplan.io.yaml
  sites/old-docs.jujucharms.com.yaml
  sites/old-docs.maas.io.yaml
  sites/releases.demo.haus.yaml
  sites/sdrsatcom.snapcraft.io.yaml
  sites/tutorials.ubuntu.com.yaml
  sites/usn.ubuntu.com.yaml
  sites/vanillaframework.io.yaml
Labels: Review: Code needed

#291 Replicas as mandatory property
  create-project
  konf.py
  sites/360.canonical.com.yaml
  sites/README.md
  sites/canonical.com.yaml
  sites/certification.ubuntu.com.yaml
  sites/charmed-osm.com.yaml
  sites/cloud-init.io.yaml
  sites/cn.ubuntu.com.yaml
  sites/conjure-up.io.yaml
  sites/design.ubuntu.com.yaml
  sites/docs.conjure-up.io.yaml
  sites/docs.ubuntu.com.yaml
  sites/docs.vanillaframework.io.yaml
  sites/dqlite.io.yaml
  sites/engage.canonical.com.yaml
  sites/etclite.io.yaml
  sites/jaas.ai.yaml
  sites/jp.ubuntu.com.yaml
  sites/juju.is.yaml
  sites/jujucharms.com.yaml
  sites/kubeflow-news.com.yaml
  sites/limenet.snapcraft.io.yaml
  sites/maas.io.yaml
  sites/manager.assets.ubuntu.com.yaml
  sites/microk8s.io.yaml
  sites/microstack.run.yaml
  sites/mir-server.io.yaml
  sites/multipass.run.yaml
  sites/netplan.io.yaml
  sites/old-docs.jujucharms.com.yaml
  sites/old-docs.maas.io.yaml
  sites/releases.demo.haus.yaml
  sites/sdrsatcom.snapcraft.io.yaml
  sites/snapcraft.io.yaml
  sites/staging-api.snapcraft.io.yaml
  sites/tutorials.ubuntu.com.yaml
  sites/ubuntu.com.yaml
  sites/usn.ubuntu.com.yaml
  sites/vanillaframework.io.yaml
  templates/deployment.yaml
  templates/ingress.yaml
  templates/site.yaml
Labels: Review: Code +1, Review: QA +1

#285 Allow-origin * for /blog/latest-news
  sites/ubuntu.com.yaml
  templates/site.yaml
Labels: Review: Code needed, Review: QA needed

#293 Update README.md
  README.md
  sites/README.md
Labels: Review: Code +1

#294 Support query strings on /blog/latest-news
  sites/ubuntu.com.yaml
Labels: Review: Code needed, Review: QA +1

#295 For staging too =)
  sites/ubuntu.com.yaml
Labels: Review: Code +1

#296 Anbox k8s config
  sites/anbox-cloud.io.yaml
Labels: Review: Code +1, Review: QA +1

#297 Add sentry to k8s for anbox
  sites/anbox-cloud.io.yaml
Labels: Review: Code +1
