Repository canonical/deployment-configs, pull requests merged in 2019-03, with the labels that each got.

#202 Add github secret token to webhook service
  services/webteam-kpi-webhook-canonical-com.yaml
Labels: Review: Code +1

#204 Add old-docs.jujucharms.com config
  ingresses/production/old-docs-jujucharms-com.yaml
  ingresses/staging/old-docs-staging-jujucharms-com.yaml
  services/old-docs-jujucharms-com.yaml
Labels: Review: Code +1

#203 Update string to int for http-redirect-code
  config.global.yaml
Labels: Review: Code needed

#205 Remove discourse docs staging (unuseD)
  ingresses/staging/docs-staging-snapcraft-io.yaml
Labels: Review: Code +1, Review: QA +1
