Repository canonical/deployment-configs, pull requests merged in 2019-05, with the labels that each got.

#212 Create jujucharms configs
  ingresses/production/jujucharms-com.yaml
  ingresses/staging/staging-jujucharms-com.yaml
  services/jujucharms-com.yaml
Labels: Review: Code -1, Review: QA +1

#213 Make ingress for ubuntu-com.internal
  ingresses/production/ubuntu-com-internal.yaml
  services/ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#214 Configs for releases.demo.haus
  ingresses/staging/releases-demo-haus.yaml
  services/releases-demo-haus.yaml
Labels: Review: Code needed, Review: QA needed

#217 Handle [www.]microk8s.com
  ingresses/production/microk8s-io.yaml
Labels: Review: Code +1

#218 Make the lines prettier for microk8s ingress
  ingresses/production/microk8s-io.yaml
Labels: Review: Code +1, Review: QA +1
