Repository canonical/deployment-configs, pull requests merged in 2019-10, with the labels that each got.

#253 Try pre-connecting to useful domains
  ingresses/production/ubuntu-com.yaml
  ingresses/staging/staging-ubuntu-com.yaml
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#250 Simplify snapcraft.io config
  services/snapcraft-io.yaml
  services/staging-api-snapcraft-io.yaml
Labels: Review: Code needed, Review: QA needed

#258 Remove crossorigin for preconnects
  ingresses/production/ubuntu-com.yaml
  ingresses/staging/staging-ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#257 Enable brotli compression
  configmaps/nginx-configuration.yaml
  qa-deploy
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#256 Re-enable HTTP/2
  configmaps/nginx-configuration.yaml
Labels: Performance ⚡️, Review: Code +1, Review: QA +1

#255 Enable TLSv1.3
  configmaps/nginx-configuration.yaml
Labels: Performance ⚡️, Review: Code needed, Review: QA needed

#260 Change rooms for bot
  services/webteam-ircbot-canonical-com.yaml
Labels: Review: Code +1

#263 Configure ubuntu.com ingress for both HTTP & HTTPS support
  ingresses/production/blog-ubuntu-com.yaml
  ingresses/production/ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#261 Add dashboard.staging.jaas.ai
  ingresses/staging/dashboard-staging-jaas-ai.yaml
  services/dashboard-jaas-ai.yaml
Labels: Review: Code +1, Review: QA +1

#266 Add is-outage irc room for release notification
  services/webteam-ircbot-canonical-com.yaml
Labels: Review: Code +1

#267 Add configs for manager.assets.ubuntu.com
  ingresses/production/manager-assets-ubuntu-com.yaml
  ingresses/staging/manager-staging-assets-ubuntu.yaml
  services/manager-assets-ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#268 Add missing part of asset manager staging domain
  ingresses/staging/manager-staging-assets-ubuntu-com.yaml
Labels: Review: Code +1

#271 Remove unused domains
  ingresses/production/developer-ubuntu-com.yaml
Labels: Review: Code +1

#273 Fix typo for docs.staging.maas.io
  ingresses/staging/staging-maas-io.yaml
Labels: Review: Code +1

#274 Use correct domain for staging asset manager
  ingresses/staging/manager-assets-staging-ubuntu-com.yaml
Labels: Review: Code needed, Review: QA needed

#276 Add configs for charmed-osm.com
  ingresses/production/charmed-osm-com.yaml
  ingresses/staging/staging-charmed-osm-com.yaml
  services/charmed-osm-com.yaml
Labels: Review: Code +1, Review: QA +1
