Repository canonical/deployment-configs, pull requests merged in 2019-08, with the labels that each got.

#240 Disable HTTP2 for main NGINX controller
  config.global.yaml
Labels: Review: Code +1, Review: QA +1

#241 Add certification.ubuntu.com configuration
  ingresses/production/certification-ubuntu-com.yaml
  ingresses/staging/certification-staging-ubuntu-com.yaml
  services/certification-ubuntu-com.yaml
Labels: Review: Code needed, Review: QA needed

#243 Use 5 replicas for certification
  services/certification-ubuntu-com.yaml
Labels: Review: Code +1, Review: QA +1

#244 Increase memory allocation for ubuntu.com
  services/ubuntu-com.yaml
Labels: Review: Code +1
