Repository canonical/deployment-configs, pull requests merged in 2019-09, with the labels that each got.

#246 A separate service for ubuntu.com/blog
  ingresses/production/ubuntu-com.yaml
  ingresses/staging/staging-ubuntu-com.yaml
  qa-deploy
  services/ubuntu-com-blog.yaml
Labels: Review: Code +1, Review: QA +1

#247 Configs for microstack.run
  ingresses/production/microstack-run.yaml
  ingresses/staging/staging-microstack-run.yaml
  qa-deploy
  services/microstack-run.yaml
Labels: Review: Code +1, Review: QA +1

#248 Config for juju.is
  ingresses/production/juju-is.yaml
  ingresses/staging/staging-juju-is.yaml
  services/juju-is.yaml
Labels: Review: Code +1, Review: QA +1

#251 Double memory for snapcraft-io containers
  services/snapcraft-io.yaml
Labels: Review: Code +1

#249 Consolidate global config for services
  config.production.yaml
  configmaps/global-envvars.yaml
  configmaps/nginx-configuration.yaml
  configmaps/proxy-config.yaml
  create-project
  qa-deploy
  services/canonical-com.yaml
  services/certification-ubuntu-com.yaml
  services/cloud-init-io.yaml
  services/cn-ubuntu-com.yaml
  services/conjure-up-io.yaml
  services/design-ubuntu-com.yaml
  services/developer-ubuntu-com.yaml
  services/docs-conjure-up-io.yaml
  services/docs-ubuntu-com-core.yaml
  services/docs-ubuntu-com-phone.yaml
  services/docs-ubuntu-com-security-certs.yaml
  services/docs-ubuntu-com.yaml
  services/docs-vanillaframework-io.yaml
  services/dqlite-io.yaml
  services/engage-canonical-com.yaml
  services/etclite-io.yaml
  services/jaas-ai.yaml
  services/jp-ubuntu-com.yaml
  services/jujucharms-com.yaml
  services/kubeflow-news-com.yaml
  services/landscape-brochure-internal.yaml
  services/limenet-snapcraft-io.yaml
  services/maas-io.yaml
  services/microk8s-io.yaml
  services/microstack-run.yaml
  services/mir-server-io.yaml
  services/multipass-run.yaml
  services/netplan-io.yaml
  services/old-docs-jujucharms-com.yaml
  services/old-docs-maas-io.yaml
  services/releases-demo-haus.yaml
  services/sdrsatcom-snapcraft-io.yaml
  services/snapcraft-io.yaml
  services/staging-api-snapcraft-io.yaml
  services/tutorials-ubuntu-com.yaml
  services/ubuntu-com-blog.yaml
  services/ubuntu-com.yaml
  services/usn-ubuntu-com.yaml
  services/vanillaframework-io.yaml
  services/webteam-kpi-webhook-canonical-com.yaml
  templates/service.yaml
Labels: Review: Code needed, Review: QA needed

#252 Add IRC bot deployement config
  ingresses/production/webteam-ircbot-canonical-com.yaml
  qa-deploy
  services/webteam-ircbot-canonical-com.yaml
Labels: Review: Code +1, Review: QA +1
