Repository canonical/deployment-configs, pull requests merged in 2020-05, with the labels that each got.

#367 Set hbd.360reviews.io image to use dots instead of dashes
  sites/hbd.360reviews.io.yaml
Labels: Review: Code +1

#369 Revert docker name change
  sites/limenet.snapcraft.io.yaml
  sites/sdrsatcom.snapcraft.io.yaml
Labels: Review: Code +1

#370 Konf strict snap
  .github/workflows/tests.yaml
  setup.py
  snapcraft.yaml
Labels: Review: Code needed, Review: QA needed

#371 Changes for the demo service
  konf.py
  templates/deployment.yaml
  templates/ingress.yaml
Labels: Review: Code +1, Review: QA +1

#374 Add Charmhub to the proxy list
  templates/proxy-settings.yaml
Labels: Review: Code +1

#375 Charmhub: Add secret for SSO
  sites/charmhub.io.yaml
Labels: Review: Code +1

#377 Fix typo docker image name
  sites/sdrsatcom.snapcraft.io.yaml
Labels: Review: Code +1

#372 Fix Snap to include the templates folder
  snapcraft.yaml
Labels: Review: Code +1, Review: QA +1

#378 Change room from base-squad to webteam-dev
  cronjobs/webteam-ircbot-review-notifier.yaml
  sites/webteam-ircbot.canonical.com.yaml
Labels: Review: Code +1, Review: QA +1

#379 Update templates to be compatible with k8s 1.16
  konf.py
  templates/deployment.yaml
  templates/ingress.yaml
Labels: Review: Code +1, Review: QA +1

#380 Add extra more domains
  sites/conjure-up.io.yaml
  sites/design.ubuntu.com.yaml
Labels: Review: Code +1
