Repository canonical/deployment-configs, pull requests merged in 2020-01, with the labels that each got.

#300 Improve qa-deploy script output
  qa-deploy
Labels: Review: Code +1, Review: QA +1

#302 Add secret_key for anbox cloud
  sites/anbox-cloud.io.yaml
Labels: Review: Code +1

#304 Add the jaas-dashboard to jaas.ai
  .gitignore
  sites/docs.ubuntu.com.yaml
  sites/jaas.ai.yaml
  sites/ubuntu.com.yaml
  templates/deployment.yaml
  templates/ingress.yaml
  templates/service.yaml
  templates/site.yaml
Labels: Review: Code +1, Review: QA +1

#305 emergency fix
  sites/ubuntu.com.yaml
Labels: Review: QA needed

#307 Fix tabulations
  templates/site.yaml
Labels: Review: Code +1

#308 Added greenhouse secret
  sites/canonical.com.yaml
Labels: Review: Code +1

#309 Remove dashboard routes from jaas.ai
  sites/jaas.ai.yaml
Labels: Review: Code +1

#306 Add tutorials to u.com
  sites/ubuntu.com.yaml
Labels: Review: Code +1, Review: QA +1

#313 Validate Kubernetes output with GitHub Actions
  .github/workflows/validate.yml
  sites/staging-api.snapcraft.io.yaml
Labels: Review: Code +1

#315 Redirect tutorials to new site
  sites/tutorials.ubuntu.com.yaml
  sites/ubuntu.com.yaml
Labels: Review: Code +1, Review: QA +1

#312 Add GitHub and Launchpad secrets for Snapcraft
  sites/snapcraft.io.yaml
Labels: Review: Code +1
