Repository canonical/deployment-configs, pull requests merged in 2020-07, with the labels that each got.

#373 Add partners site configuration
  sites/partners.ubuntu.com.yaml
Labels: Project, Review: Code +1

#392 Remove all site config files
  .github/workflows/validate.yml
  sites/360.canonical.com.yaml
  sites/README.md
  sites/anbox-cloud.io.yaml
  sites/canonical.com.yaml
  sites/certification.ubuntu.com.yaml
  sites/charmed-osm.com.yaml
  sites/charmhub.io.yaml
  sites/cloud-init.io.yaml
  sites/cn.ubuntu.com.yaml
  sites/conjure-up.io.yaml
  sites/design.ubuntu.com.yaml
  sites/docs.conjure-up.io.yaml
  sites/docs.ubuntu.com.yaml
  sites/dqlite.io.yaml
  sites/etclite.io.yaml
  sites/hbd.360reviews.io.yaml
  sites/imagebuilder.demo.haus.yaml
  sites/jaas.ai.yaml
  sites/jp.ubuntu.com.yaml
  sites/juju.is.yaml
  sites/jujucharms.com.yaml
  sites/kubeflow-news.com.yaml
  sites/limenet.snapcraft.io.yaml
  sites/maas.io.yaml
  sites/manager.assets.ubuntu.com.yaml
  sites/microk8s.io.yaml
  sites/microstack.run.yaml
  sites/mir-server.io.yaml
  sites/multipass.run.yaml
  sites/netplan.io.yaml
  sites/old-docs.jujucharms.com.yaml
  sites/old-docs.maas.io.yaml
  sites/partners.ubuntu.com.yaml
  sites/releases.demo.haus.yaml
  sites/sdrsatcom.snapcraft.io.yaml
  sites/snapcraft.io.yaml
  sites/staging-api.snapcraft.io.yaml
  sites/ubuntu.com.yaml
  sites/usn.ubuntu.com.yaml
  sites/vanillaframework.io.yaml
  sites/webteam-ircbot.canonical.com.yaml
Labels: Review: Code +1, Review: QA +1

#393 Allow passing of database URL
  .github/workflows/tests.yaml
  konf.py
Labels: Review: Code +1, Review: QA +1

#394 Remove konf snap files
  .github/workflows/publish.yaml
  .github/workflows/tests.yaml
  .gitignore
  create-project
  konf.py
  qa-deploy
  renovate.json
  requirements.txt
  setup.py
  snapcraft.yaml
  templates/cronjob.yaml
  templates/deployment.yaml
  templates/ingress.yaml
  templates/proxy-settings.yaml
  templates/service.yaml
  templates/site.yaml
Labels: Review: Code needed
