Repository canonical/deployment-configs, pull requests merged in 2020-04, with the labels that each got.

#341 Poller script
  cronjobs/snapcraft-poller-script.yaml
  templates/cronjob.yaml
Labels: Review: Code +1, Review: QA +1

#343 Add domains
  sites/canonical.com.yaml
  sites/snapcraft.io.yaml
  sites/ubuntu.com.yaml
Labels: Review: Code +1

#345 Added default env vars for cronjobs
  templates/cronjob.yaml
Labels: Review: Code +1

#346 Add developer.ubuntu.com
  sites/ubuntu.com.yaml
Labels: Review: Code +1

#347 Add www.font.ubuntu.com
  sites/design.ubuntu.com.yaml
  sites/ubuntu.com.yaml
Labels: Review: Code +1

#348 Rename feedinghopeandheroes.org to feedourfrontline.org
  sites/feedinghopeandheroes.org.yaml
  sites/feedourfrontline.org.yaml
Labels: Review: Code +1

#342 Snap up konf.py
  create-project
  konf.py
  qa-deploy
  setup.py
  snapcraft.yaml
Labels: Review: Code +1, Review: QA +1

#351 Update env variable for staging-api.snapcraft.io
  sites/staging-api.snapcraft.io.yaml
Labels: Review: Code +1

#352 Added proxy-settings sub-template
  cronjobs/snapcraft-poller-script.yaml
  templates/cronjob.yaml
  templates/deployment.yaml
  templates/proxy-settings.yaml
Labels: Review: Code +1, Review: QA +1

#353 Add secrets for vanilla framework
  sites/vanillaframework.io.yaml
Labels: Review: Code +1

#354 Add SECRET_KEY for charmhub.io
  sites/charmhub.io.yaml
Labels: Review: Code +1

#355 Force secret key on template generation
  sites/360.canonical.com.yaml
  sites/anbox-cloud.io.yaml
  sites/charmhub.io.yaml
  sites/engage.canonical.com.yaml
  sites/manager.assets.ubuntu.com.yaml
  sites/snapcraft.io.yaml
  sites/staging-api.snapcraft.io.yaml
  sites/vanillaframework.io.yaml
  templates/deployment.yaml
Labels: Review: Code +1, Review: QA +1

#357 Added IRC bot cronjobs
  cronjobs/webteam-ircbot-review-notifier.yaml
  cronjobs/webteam-ircbot-support-updater.yaml
  templates/cronjob.yaml
Labels: Review: Code +1, Review: QA +1

#358 Remove feedourfrontline.org conf files
  sites/feedourfrontline.org.yaml
Labels: Review: Code +1

#359 Remove engage.canonical.com
  sites/engage.canonical.com.yaml
Labels: Review: Code needed

#360 Env variable for charmhub
  sites/charmhub.io.yaml
Labels: Review: Code +1

#361 Add config for imagebuilder demo
  sites/imagebuilder.demo.haus.yaml
Labels: Review: Code +1

#362 Add imagebuild secrets, ready for imagebuilder
  sites/ubuntu.com.yaml
Labels: Review: Code +1, Review: QA +1

#363 Add config for HBD
  sites/hbd.360reviews.io.yaml
Labels: Review: Code +1, Review: QA +1

#365 Add secret google service account
  sites/hbd.360reviews.io.yaml
Labels: Review: Code needed

#364 Add env webapp
  sites/limenet.snapcraft.io.yaml
  sites/sdrsatcom.snapcraft.io.yaml
Labels: Review: Code +1, Review: QA +1

#366 Add dqlite.io to no proxyy
  templates/proxy-settings.yaml
Labels: Review: Code +1, Review: QA +1
