Repository canonical/deployment-configs, pull requests merged in 2020-03, with the labels that each got.

#324 Redirect docs.vanillaframework.io -> vanllaframework.io/docs
  sites/docs.vanillaframework.io.yaml
  sites/vanillaframework.io.yaml
Labels: Review: Code +1, Review: QA +1

#325 Added SEARCH_API_KEY for vanillaframework
  sites/vanillaframework.io.yaml
Labels: Review: Code +1

#326 Add secret for the USN database URL
  sites/ubuntu.com.yaml
Labels: Review: Code +1

#328 Deployment config for charmhub.io
  sites/charmhub.io.yaml
Labels: Review: Code +1, Review: QA needed

#329 Change irc bot port
  sites/webteam-ircbot.canonical.com.yaml
Labels: Review: Code needed

#335 Remove unused environment variables
  sites/360.canonical.com.yaml
Labels: Review: Code +1

#336 CronJob support
  konf.py
  templates/cronjob.yaml
Labels: Review: Code +1, Review: QA +1

#337 Config for feedinghopeandheroes.org
  sites/feedinghopeandheroes.org.yaml
Labels: Review: Code +1, Review: QA +1

#338 fstring is not supported in Jenkins
  konf.py
Labels: Review: Code +1
