Repository canonical/deployment-configs, pull requests merged in 2020-06, with the labels that each got.

#381 Requests to *.internal don't need to be proxied
  templates/proxy-settings.yaml
Labels: Review: Code +1

#382 Proxy for microk8s installer
  .gitignore
  sites/microk8s.io.yaml
  templates/ingress.yaml
Labels: Review: Code +1, Review: QA +1

#384 Add docs.conjure-up.[org|com|net]
  sites/docs.conjure-up.io.yaml
Labels: Review: QA +1

#383 Create publish.yaml
  .github/workflows/publish.yaml
  .github/workflows/tests.yaml
Labels: Review: Code +1
